name: deploy-auth

on:
  push:
    branches: 
      - master
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t alonmyburgh/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKERPASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push alonmyburgh/auth
